version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: questionario_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://db:5432/questionario_db
      DB_USERNAME: user
      DB_PASSWORD: password
    command: ["java", "-jar", "app.jar"]

volumes:
  pgdata:
